services:
  bronson:
    container_name: bronson
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1968:1968"
    environment:
      - PROMETHEUS_MULTIPROC_DIR=/tmp
      - ENABLE_METRICS=true
      - CLEANUP_DIRECTORY=/data
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
