version: '3.8'

services:
  brronson:
    container_name: brronson
    build: .
    ports:
      - "1968:1968"
    environment:
      - CLEANUP_DIRECTORY=/cleanup
      - TARGET_DIRECTORY=/target
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - LOG_FILE=brronson.log
    volumes:
      - ./cleanup:/cleanup
      - ./target:/target
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: brronson-redis
    ports:
      - "6379:6379"
