services:
  bronson:
    container_name: bronson
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1968:1968"
    environment:
      - PROMETHEUS_MULTIPROC_DIR=/tmp
      - ENABLE_METRICS=true
      - CLEANUP_DIRECTORY=/data
      - TARGET_DIRECTORY=/target
      - LOG_LEVEL=INFO
      - LOG_FILE=bronson.log
      - LOG_FORMAT=%(asctime)s - %(name)s - %(levelname)s - %(message)s
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
