services:
  redis:
    image: redis:7-alpine
    container_name: bronson-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  bronson:
    container_name: bronson
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1968:1968"
    environment:
      - PROMETHEUS_MULTIPROC_DIR=/tmp
      - ENABLE_METRICS=true
      - CLEANUP_DIRECTORY=/data
      - TARGET_DIRECTORY=/target
      - LOG_LEVEL=INFO
      - LOG_FILE=bronson.log
      - LOG_FORMAT=%(asctime)s - %(name)s - %(levelname)s - %(message)s
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    restart: unless-stopped
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"

  worker:
    container_name: bronson-worker
    build:
      context: .
      dockerfile: Dockerfile
    command: python worker.py
    environment:
      - LOG_LEVEL=INFO
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - /data:/data
      - /target:/target

volumes:
  redis_data:
